#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the navbar)
name: 'Tatsuta Recipes'

# Your site's title (e.g., Ben's Awesome Site, The GitHub Blog, etc.), used as part of the title tag like Home | Ben's Awesome Site.
title: 'Tatsuta Recipes'


# The full URL to your site. Note: site.github.url will be used by default.
url: https://github.com/TatsutaScott

baseurl: /recipes
permalink: /:title
# global author information
author: Scott Tatsuta

# Includes an icon in the footer for each username you enter
footer-links:
  email: tatsuta.scott@gmail.com
  github: TatsutaScott
  instagram: 
  linkedin: 

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

theme: jekyll-theme-tactile
